controller:
  admin:
    username: admin
    password: qwert123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - docker-plugin:latest
    - docker-workflow:latest
    - job-dsl:latest

  serviceAccount:
    name: jenkins-sa
    create: false

  JCasC:
    configScripts:
      seed-job: |
        jobs:
          - script: >
              job('seed-job') {
                description('Job to generate pipeline for Django project')
                scm {
                  git {
                    remote {
                      url('https://github.com/cod3provider/woolf-microservice-project.git')
                    }
                    branches('*/lesson-4')
                  }
                }
                steps {
                  dsl {
                    text('''
                      pipelineJob("django-docker") {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("https://github.com/cod3provider/woolf-microservice-project.git")
                                }
                                branches("*/lesson-4")
                              }
                            }
                          }
                        }
                      }
                    ''')
                  }
                }
              }