applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/cod3provider/woolf-microservice-project.git
      path: lesson-8-9/charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/cod3provider/woolf-microservice-project.git
    username:
    password:

repoConfig:
  insecure: "true"
  enableLfs: "true"