applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/cod3provider/woolf-microservice-project.git
      path: final_project/charts/django-app
      targetRevision: final_project
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
