apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
          - name: postgres
            image: postgres:13
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_DB
                value: "{{ .Values.config.DATABASE_NAME }}"
              - name: POSTGRES_USER
                value: "{{ .Values.config.DATABASE_USERNAME }}"
              - name: POSTGRES_PASSWORD
                value: "{{ .Values.config.DATABASE_PASSWORD }}"
            volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc